matrix:
  include:
    - env: PLATFORM=debian-jessie ORIGIN=default VENDOR=mysql
    - env: PLATFORM=debian-jessie ORIGIN=default VENDOR=mariadb
    - env: PLATFORM=debian-jessie ORIGIN=uptream VENDOR=mariadb
    - env: PLATFORM=debian-jessie ORIGIN=uptream VENDOR=mariadb_galera
    - env: PLATFORM=debian-jessie ORIGIN=uptream VENDOR=percona

sudo: required

language: python

script:
  - docker build -f tests/$PLATFORM.Dockerfile -t test-$PLATFORM . && docker run -e "ORIGIN=$ORIGIN" -e "VENDOR=$VENDOR" --name $PLATFORM test-$PLATFORM

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
