---

- name: TEMPLATE | Deploy Galera configuration
  template: src=etc/mysql/conf.d/09-galera.cnf.j2 dest=/etc/mysql/conf.d/09-galera.cnf
  register: galeraconfig

- name: INCLUDE | Bootstrap first node
  include: 'bootstrap.yml'
  when: inventory_hostname == mysql_galera_primary_node

- name: INCLUDE | Configure other nodes
  include: 'nodes.yml'
  when: inventory_hostname != mysql_galera_primary_node

- name: SERVICE | Restart MariaDB if needed
  service: name=mysql state=restarted
  when: >
    (galeraconfig or (p is defined and p.changed)) and
    (bootstrap_run is not defined)
